version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: account,acm,acm-pca,apigateway,apigatewaymanagementapi,apigatewayv2,autoscaling,es,firehose,cloudformation,cloudtrail,cloudwatch,dynamodb,dynamodbstreams,ebs,ec2,ec2-instance-connect,ecr,ecr-public,ecs,efs,eks,elastic-inference,elb,elbv2,events,iam,kafka,kafkaconnect,kms,lambda,pricing,rds,rds-data,route53,route53domains,route53resolver,s3,s3api,secretsmanager,sms,sns,sqs,ssm,sts
      DEFAULT_REGION: ${AWS_REGION:-us-west-2}
      AWS_DEFAULT_REGION: ${AWS_REGION:-us-west-2}
      EDGE_PORT: 4566
      HOSTNAME_EXTERNAL: localstack
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY:-}
      DEBUG: 1
    privileged: true
    ports:
      - '4566:4566'
    networks:
      - internal
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  internal: